#! /bin/sh

### BEGIN INIT INFO
# Provides:				uptime-httpd
# Required-Start:		$remote_fs $syslog
# Required-Stop:		$remote_fs $syslog
# Should-Start:			$network
# Should-Stop:			$network
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Uptime HTTPd
# Description:			Starts the Uptime HTTPd service in the background
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

GOPATH="/path/to/this/project"

UHTTPD="$GOPATH/bin/uptime-httpd"
UHTTPD_NAME="uptime-httpd"
UHTTPD_PID="/var/run/$UHTTPD_NAME.pid"
UHTTPD_LOG_DIR="$/var/log/$UHTTPD_NAME" ; mkdir -p $UHTTPD_LOG_DIR
UHTTPD_LOG_FILE="$UHTTPD_LOG_DIR/$UHTTPD_NAME.log"

SSD_PARAMS="--quiet --oknodo --pidfile $UHTTPD_PID"

set -e
test -x $UHTTPD || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting Uptime HTTPd service" "$UHTTPD_NAME" || true
		if start-stop-daemon --start $SSD_PARAMS --make-pidfile --background --no-close --exec $UHTTPD >> $UHTTPD_LOG_FILE 2>&1; then
			log_end_msg 0 || true
		else
			log_end_msg 1 || true
		fi
		;;

	stop)
		log_daemon_msg "Stopping Uptime HTTPd service" "$UHTTPD_NAME" || true
		if start-stop-daemon --stop --retry 10 $SSD_PARAMS; then
			log_end_msg 0 || true
		else
			log_end_msg 1 || true
		fi
		;;

	restart)
		$0 stop
		$0 start
		;;

	status)
		status_of_proc -p $UHTTPD_PID $UHTTPD $UHTTPD_NAME && exit 0 || exit $?
		;;

	*)
		log_action_msg "Usage: /etc/init.d/$UHTTPD_NAME {start|stop|restart|status}" || true
		exit 1
esac

exit 0